# Will automatically build and push new docker image on release

name: Build and Publish Docker image on on master push and publish of release

on:
  release:
    types: [published]
  push:
    branches:
      - master

jobs:
  build_and_push:
    name: Push Docker image to multiple registries if necessary
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta_extract
        uses: docker/metadata-action@v3
        with:
          images: |
            ghcr.io/${{ github.repository }}
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=sha,enable=true,priority=100,prefix=,suffix=,format=short
            type=ref,enable=true,priority=600,prefix=,suffix=,event=branch
            type=ref,enable=true,priority=600,prefix=,suffix=,event=tag
            type=ref,enable=true,priority=600,prefix=pr-,suffix=,event=pr
          labels: |
            org.opencontainers.image.url=https://ctid.mitre-engenuity.org/

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ steps.meta_extract.outputs.tags }}
          labels: ${{ steps.meta_extract.outputs.labels }}
